layout_spectrum: 0.8762952
typography_spectrum: 0.9325442
color:
  saturation: 0.01848761
  lightness: 0.5196841
  brandStrength: 0.03538965
  rhythmicContrast: 0.1142114
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Flipje
